onlyOneBackUp: 1
defaultIndent: "    "
indentAfterItems:
    itemize: 0
    enumerate: 0
    description: 0
    list: 0
indentAfterHeadings:
    chapter:
        indentAfterThisHeading: 1
        level: 1
    section:
        indentAfterThisHeading: 1
        level: 2
    section*:
        indentAfterThisHeading: 1
        level: 2
indentRules:
    chapter: "    "
    section: "    "
